apiVersion: v1
kind: Service
metadata:
  name: sitas-backend
  namespace: sitas
  labels:
    app: sitas-backend
spec:
  type: LoadBalancer
  selector:
    app: sitas-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31001