apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitas-backend
  namespace: sitas
spec:
  selector:
    matchLabels:
      app: sitas-backend
  template:
    metadata:
      labels:
        app: sitas-backend
    spec:
      containers:
        - name: sitas-backend
          image: oscarvicente/sitas-backend-prod
          imagePullPolicy: Always
          env:
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sitas-backend-secret
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: sitas-backend-secret
                  key: GOOGLE_SECRET
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sitas-backend-secret
                  key: GITHUB_CLIENT_ID
            - name: GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: sitas-backend-secret
                  key: GITHUB_SECRET
            - name: DISCORD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sitas-backend-secret
                  key: DISCORD_CLIENT_ID
            - name: DISCORD_SECRET
              valueFrom:
                secretKeyRef:
                  name: sitas-backend-secret
                  key: DISCORD_SECRET
            - name: LOGIN_FRONT_REDIRECT
              value: "http://oscarvx00.ddns.net:31000"
            - name: MONGODB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: sitas-backend-secret
                  key: MONGODB_ENDPOINT
            - name: MONGODB_DATABASE
              value: sitas-prod
            - name: DOWNLOAD_REQUEST_QUEUE
              value: download-request-prod
            - name: AZURE_SERVICE_BUS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: sitas-backend-secret
                  key: AZURE_SERVICE_BUS_CONNECTION_STRING