spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_SECRET}
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET}
          discord:
            client-id: ${DISCORD_CLIENT_ID}
            client-secret: ${DISCORD_SECRET}
            authorization-grant-type: authorization_code
            clientAuthenticationMethod: post
            redirectUri: "{baseUrl}/login/oauth2/code/discord"
            scope:
              - identify

        provider:
          github:
            userNameAttribute: login
          discord:
            name: discord
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            revokeTokenUri: https://discord.com/api/oauth2/token/revoke
            userNameAttribute: username